// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9hnrOFR2I0fNHxRvGqD1-H3dQriFkOWU',
    appId: '1:283783513278:web:2eb99e016d2bd80ec80aef',
    messagingSenderId: '283783513278',
    projectId: 'dailyhealthtrackermtbc',
    authDomain: 'dailyhealthtrackermtbc.firebaseapp.com',
    storageBucket: 'dailyhealthtrackermtbc.firebasestorage.app',
    measurementId: 'G-LW6310Q3SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIGFTO8H7BTdv65uX73AdVLZxLXsug3Ls',
    appId: '1:283783513278:android:d2046d8000778c97c80aef',
    messagingSenderId: '283783513278',
    projectId: 'dailyhealthtrackermtbc',
    storageBucket: 'dailyhealthtrackermtbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiLsBBdln_ZuVVRLEfOGWit_VGwHHUbtU',
    appId: '1:283783513278:ios:6d8dc8a3022e1fa6c80aef',
    messagingSenderId: '283783513278',
    projectId: 'dailyhealthtrackermtbc',
    storageBucket: 'dailyhealthtrackermtbc.firebasestorage.app',
    iosBundleId: 'com.example.dailyhealthtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiLsBBdln_ZuVVRLEfOGWit_VGwHHUbtU',
    appId: '1:283783513278:ios:acc35132a7f42aa3c80aef',
    messagingSenderId: '283783513278',
    projectId: 'dailyhealthtrackermtbc',
    storageBucket: 'dailyhealthtrackermtbc.firebasestorage.app',
    iosBundleId: 'com.example.dailyHealthTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9hnrOFR2I0fNHxRvGqD1-H3dQriFkOWU',
    appId: '1:283783513278:web:fe3af6b994e3f9f6c80aef',
    messagingSenderId: '283783513278',
    projectId: 'dailyhealthtrackermtbc',
    authDomain: 'dailyhealthtrackermtbc.firebaseapp.com',
    storageBucket: 'dailyhealthtrackermtbc.firebasestorage.app',
    measurementId: 'G-46JB5DWBZ2',
  );
}
